trigger:
- master

pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: "ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2"
  inputs:
    toolMajorVersion: 'V2'