jobs:
- job: validate_pr
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      feedsToUse: 'select'
      vstsFeed: '/3af14e61-2fb2-458a-8c64-e719475681c4'
      versioningScheme: 'off'
      arguments: 'install $(ossvalidatorspkg) -Version $(ossvalidatorsversion) -OutputDirectory $(Agent.BuildDirectory)'
      includeNuGetOrg: false
  - powershell: |
      $SourceRepo = [System.Uri]$Env:SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI
      $SourceRepo = $SourceRepo.AbsolutePath -replace '.git'

      $GitUrl = '$(githubapi)' + $SourceRepo + '/pulls/' + $Env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER + '/files'

      # Get the list of files for the given PR
      $Files = Invoke-RestMethod -Uri $GitUrl -Method Get

      ForEach ($File in $Files) {
        $filename = $File.filename
        if($filename.EndsWith('.swagger.json')) {
          $(Agent.BuildDirectory)/$(ossvalidatorspkg).$(ossvalidatorsversion)/$(swaggervalidator) $filename

          # Error encountered
          if($LastExitCode)
          {
            exit $LastExitCode
          }
        }
      }
